package com.rest_service.commons.enums

enum class EventType {
    USER_CREATE_START,
    USER_CREATE_INITIATE,
    USER_CREATE_APPROVE,
    USER_CREATE_REJECT,
    USER_CREATE_COMPLETE,
    USER_CREATE_ERROR,

    ROOM_CREATE_START,
    ROOM_CREATE_INITIATE,
    ROOM_CREATE_APPROVE,
    ROOM_CREATE_REJECT,
    ROOM_CREATE_COMPLETE,
    ROOM_CREATE_ERROR,

    MESSAGE_CREATE_START,
    MESSAGE_CREATE_INITIATE,
    MESSAGE_CREATE_APPROVE,
    MESSAGE_CREATE_REJECT,
    MESSAGE_CREATE_COMPLETE,
    MESSAGE_CREATE_ERROR,
}
