package com.rest_service.commons.enums

enum class SagaEventType {
    USER_CREATE_START,
    USER_CREATE_INITIATED,
    USER_CREATE_APPROVED,
    USER_CREATE_COMPLETED,
    USER_CREATE_REJECTED,
    USER_CREATE_ERROR,

    ROOM_CREATE_START,
    ROOM_CREATE_INITIATED,
    ROOM_CREATE_APPROVED,
    ROOM_CREATE_COMPLETED,
    ROOM_CREATE_REJECTED,
    ROOM_CREATE_ERROR,

    ROOM_ADD_MEMBER_START,
    ROOM_ADD_MEMBER_INITIATED,
    ROOM_ADD_MEMBER_APPROVED,
    ROOM_ADD_MEMBER_COMPLETED,
    ROOM_ADD_MEMBER_REJECTED,
    ROOM_ADD_MEMBER_ERROR,

    MESSAGE_CREATE_START,
    MESSAGE_CREATE_INITIATED,
    MESSAGE_CREATE_APPROVED,
    MESSAGE_CREATE_COMPLETED,
    MESSAGE_CREATE_REJECTED,
    MESSAGE_CREATE_ERROR,
}
